### ISSUE TITLE
How to implement this in ZF2?

### ISSUE THREAD

**Issue by Mondane** [adlogix/zf2-opensoft-rollout#1]
@tonivdv I've added this module to my ZF2 project using 

`composer require adlogix/zf2-opensoft-rollout`

without any problems, but how do I start using the module in, for instance, a controller?

Could you give a how-to?

**Comment by tonivdv** [comment]
Hi @Mondane ,

It's indeed not explained in the readme. I should probably do that :)

Meanwhile following should help to move on:

1. In your project.global.php (or any other autoload file) add a 'rollout' entry and specify how rollout should be configured. For example, we are using Doctrine and thus the config would be:

```php
'rollout' => [
        'storage_service' => 'zf2_rollout_storage_doctrine',

        'doctrine_storage' => [
            'class_name' => \Adsdaq\Entity\FeatureFlag::class
        ]
    ],
```
The Entity should implement `Adlogix\Zf2Rollout\Entity\FeatureInterface`

These are the supported storage services:

- zf2_rollout_storage_array => Array storage
- zf2_rollout_storage_doctrine => Doctrine
- zf2_rollout_storage_zend_db => Zend DB

2. In your controller you can access the rollout functionalities by doing following:

```php
/** @var Rollout $rollout */
$rollout = $this->getServiceLocator()->get('zf2_rollout');

if ($rollout->isActive('some_feature')) {
    // do something
}
```

_Note that there is no administration feature, so you will have to configure the options manually in the database. Checkout Rollout itself for that._

Have fun ;)

**Comment by Mondane** [comment]
Tnx. Some extra things I had to do:

Activate the module in domains/fortune.nl/config/application.config.php by adding:
```
'Adlogix\Zf2Rollout'
```

Create the entity based on https://github.com/adlogix/zf2-opensoft-rollout/blob/master/tests/Adlogix/Zf2RolloutTest/Entity/Feature.php

So far, I've tested the following features:

```php
$rollout = $this->getServiceLocator()->get('zf2_rollout'); // Load the service
$rollout->get('MyFeature'); // Get feature, it will be created in the storage if needed.
$rollout->activate('MyFeature'); // Activate the feature, eg. set the percentage to 100
$rollout->deactivate('MyFeature'); // Deactivate the feature, eg. set the percentage to 0
$rollout->isActive('MyFeature'); // Check if the feature is active.
```

@tonivdv Rollout also supports users. How does your module link the feature to users and/or groups?

Also, could you update this package to have the latest https://github.com/opensoft/rollout release?

Are you planning on making a ZF3 module for Rollout?

**Comment by tonivdv** [comment]
Hi @Mondane ,

Honestly we only did the strict minimum at the time we needed it on the project. Currently we are not doing feature flags any more, reason we did not do any changes recently. 

That said, we are not against improvements and maintaining it. If you provide a PR we'll happily test and merge it.

Cheers

**Comment by tonivdv** [comment]
@Mondane meanwhile master is already aligned with latest rollout release. I will now make a new release of this zf module.

**Comment by tonivdv** [comment]
Hi @Mondane ,

As you can see we started doing some updates. Reason is that we are heavily using Rollout for a couple of months. You can expect more in the future.

We started adding some doc too. 

Regarding zf3 support, I guess the name of this repo is wrongly chosen :) And since we are not using zf3 we won't provide support for it soon.
